server:
  address: 0.0.0.0
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: 12345

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  mail:
    host: smtp.yandex.ru
    port: 465
    username: WalDemar32.Polk@yandex.ru
    password: fbbuikmramcpeyio
    protocol: smtps
    tls: true
    auth: true
